env                   = "dev"
aws-region            = "us-east-2"
vpc-cidr-block        = "10.16.0.0/16"
vpc-name              = "vpc"
igw-name              = "igw"
pub-subnet-count      = 3
pub-cidr-block        = ["10.16.0.0/20", "10.16.16.0/20", "10.16.32.0/20"]
pub-availability-zone = ["us-east-2a", "us-east-2b", "us-east-2c"]
pub-sub-name          = "public-subnet"
pri-subnet-count      = 3
pri-cidr-block        = ["10.16.128.0/20", "10.16.144.0/20", "10.16.160.0/20"]
pri-availability-zone = ["us-east-2a", "us-east-2b", "us-east-2c"]
pri-sub-name          = "private-subnet"
public-rt-name        = "public-route-table"
private-rt-name       = "private-route-table"
eip-name              = "elasticip-natgw"
ngw-name              = "natgw"
eks-sg                = "eks-sg"
ec2-sg                = "ec2-sg"